config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  devise_for :users
  root 'welcome#index'
  get 'dashboard' => 'users#index', as: 'user_root'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.fetch(:restaurant, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RestaurantsProject
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield :body_content

app/views/layouts/devise.html.haml
- content_for :body_content do
  .container
    = yield

= render template: 'layouts/application'

app/views/layouts/users.html.haml
- content_for :body_content do
  = render partial: "shared/navbar"
  = render partial: "shared/notices"
  = yield

= render template: 'layouts/application'

app/views/layouts/welcome.html.haml
- content_for :body_content do
  .container
    = yield

= render template: 'layouts/application'

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/shared/_navbar.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "javascript:void(0)"} Brand
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "javascript:void(0)"} Active
        %li
          %a{:href => "javascript:void(0)"} Link
        %li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html"}
            Dropdown
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "javascript:void(0)"} Action
            %li
              %a{:href => "javascript:void(0)"} Another action
            %li
              %a{:href => "javascript:void(0)"} Something else here
            %li.divider
            %li.dropdown-header Dropdown header
            %li
              %a{:href => "javascript:void(0)"} Separated link
            %li
              %a{:href => "javascript:void(0)"} One more separated link
      %form.navbar-form.navbar-left
        .form-group
          %input.form-control.col-sm-8{:placeholder => "Search", :type => "text"}/
      %ul.nav.navbar-nav.navbar-right
        %p.navbar-text
          You're logged in as
          = current_user.email
        %li
          = link_to 'Logout', destroy_user_session_path, method: :delete
        %li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html"}
            Dropdown
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "javascript:void(0)"} Action
            %li
              %a{:href => "javascript:void(0)"} Another action
            %li
              %a{:href => "javascript:void(0)"} Something else here
            %li.divider
            %li
              %a{:href => "javascript:void(0)"} Separated link

app/views/shared/_notices.html.haml
- if flash[:alert]
  .alert.alert-dismissible.alert-warning
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    %h4 Warning!
    %p= flash[:alert]
- if flash[:notice]
  .alert.alert-dismissible.alert-success
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    %p= flash[:notice]

app/views/users/index.html.haml
.col-xs-1
.col-xs-10
  .card
    .card-header
      %h3.card-title
        Popular restaurants
      %hr
    .card-body.card-block
      This is the body
.col-xs-1

app/views/welcome/index.html.haml
%h2 FLJ's app
%h3 Login links
#login-links
  %div
    = link_to 'Sign in', new_user_session_path
  %div
    = link_to 'Sign up', new_user_registration_path